CREATE TABLE users(
    user_id int GENERATED BY DEFAULT AS IDENTITY,
    email varchar UNIQUE NOT NULL,
    password varchar NOT NULL,
    role varchar NOT NULL DEFAULT 'USER',

    CONSTRAINT PK_user_user_id PRIMARY KEY (user_id)
);

CREATE TABLE basket(
    basket_id int GENERATED BY DEFAULT AS IDENTITY,
    user_id int,

    CONSTRAINT PK_basket_basket_id PRIMARY KEY (basket_id),
    CONSTRAINT FK_user_user_id FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE type(
    type_id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(64) NOT NULL UNIQUE,

    CONSTRAINT PK_type_type_id PRIMARY KEY (type_id)
);

CREATE TABLE brand(
    brand_id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(64) NOT NULL UNIQUE,

    CONSTRAINT PK_brand_brand_id PRIMARY KEY (brand_id)
);

CREATE TABLE type_to_brand(
    type_id int,
    brand_id int,

    CONSTRAINT FK_type_type_id FOREIGN KEY (type_id) REFERENCES type(type_id),
    CONSTRAINT FK_brand_brand_id FOREIGN KEY (brand_id) REFERENCES brand(brand_id)
);

CREATE TABLE device(
    device_id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    price money,
    img varchar,
    type_id int,
    brand_id int,

    CONSTRAINT PK_device_device_id PRIMARY KEY (device_id),
    CONSTRAINT FK_type_type_id FOREIGN KEY (type_id) REFERENCES type(type_id),
    CONSTRAINT FK_brand_brand_id FOREIGN KEY (brand_id) REFERENCES brand(brand_id)
);

CREATE TABLE basket_to_device(
    basket_id int,
    device_id int,

    CONSTRAINT FK_basket_basket_id FOREIGN KEY (basket_id) REFERENCES basket(basket_id),
    CONSTRAINT FK_device_device_id FOREIGN KEY (device_id) REFERENCES device(device_id)
);

CREATE TABLE device_info(
    device_info_id int GENERATED BY DEFAULT AS IDENTITY,
    device_id int,
    title varchar(255) NOT NULL,
    description varchar,

    CONSTRAINT PK_device_info_device_info_id PRIMARY KEY (device_info_id),
    CONSTRAINT FK_device_device_id FOREIGN KEY (device_id) REFERENCES device(device_id)
);

CREATE TABLE rating(
    rating_id int GENERATED BY DEFAULT AS IDENTITY,
    user_id int,
    device_id int,
    rate smallint,

    CONSTRAINT PK_rating_rating_id PRIMARY KEY (rating_id),
    CONSTRAINT FK_user_user_id FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT FK_device_device_id FOREIGN KEY (device_id) REFERENCES device(device_id)
);